### ISSUE TITLE
Build fails : checksum validation failed 

### ISSUE THREAD

**Issue by kkimurak** [TIGERs-Mannheim/AutoReferee#1]
Hi, I'm not sure where to report so I'm writing this here,  

OS : Fedora 29 x86_64 (but the problem may not be related to OS, I think)

## overview
Building AutoReferee fails due to the Checksum validation failure.  
package : com/sleepycat/je/7.5.11/je-7.5.11.jar and its pom

## detail 

Here're output messages around the warning.
```
[WARNING] Checksum validation failed, expected 03ed7dc22526efd13bafef2f73a305b8bcc0e202 but is da39a3ee5e6b4b0d3255bfef95601890afd80709 from tigers_public for https://tigers-mannheim.de/nexus/content/groups/public/com/sleepycat/je/7.5.11/je-7.5.11.pom
[WARNING] Could not validate integrity of download from https://tigers-mannheim.de/nexus/content/groups/public/com/sleepycat/je/7.5.11/je-7.5.11.pom: Checksum validation failed, expected 03ed7dc22526efd13bafef2f73a305b8bcc0e202 but is da39a3ee5e6b4b0d3255bfef95601890afd80709
[WARNING] Checksum validation failed, expected 03ed7dc22526efd13bafef2f73a305b8bcc0e202 but is da39a3ee5e6b4b0d3255bfef95601890afd80709 from tigers_public for https://tigers-mannheim.de/nexus/content/groups/public/com/sleepycat/je/7.5.11/je-7.5.11.pom
Downloaded from tigers_public: https://tigers-mannheim.de/nexus/content/groups/public/com/sleepycat/je/7.5.11/je-7.5.11.pom (0 B at 0 B/s)
[WARNING] The POM for com.sleepycat:je:jar:7.5.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```
```
[WARNING] Checksum validation failed, expected 99e82039a2a22895d72fecbf90a298873164c830 but is da39a3ee5e6b4b0d3255bfef95601890afd80709 from tigers_public for https://tigers-mannheim.de/nexus/content/groups/public/com/sleepycat/je/7.5.11/je-7.5.11.jar
[WARNING] Could not validate integrity of download from https://tigers-mannheim.de/nexus/content/groups/public/com/sleepycat/je/7.5.11/je-7.5.11.jar: Checksum validation failed, expected 99e82039a2a22895d72fecbf90a298873164c830 but is da39a3ee5e6b4b0d3255bfef95601890afd80709
[WARNING] Checksum validation failed, expected 99e82039a2a22895d72fecbf90a298873164c830 but is da39a3ee5e6b4b0d3255bfef95601890afd80709 from tigers_public for https://tigers-mannheim.de/nexus/content/groups/public/com/sleepycat/je/7.5.11/je-7.5.11.jar
Downloaded from tigers_public: https://tigers-mannheim.de/nexus/content/groups/public/com/sleepycat/je/7.5.11/je-7.5.11.jar (0 B at 0 B/s)
```

I've checked [je-7.5.11.jar and its sha1 checksum on TIGERs's repository ](https://tigers-mannheim.de/nexus/#browse/browse:public:com%2Fsleepycat%2Fje%2F7.5.11%2Fje-7.5.11.jar).  
The value is different with [je-7.5.11.jar.sh1](https://tigers-mannheim.de/nexus/repository/public/com/sleepycat/je/7.5.11/je-7.5.11.jar.sha1) as the message shows.

Additionally I've checked the size of je-7.5.11.jar, it was 0. 

## test  
```
# failed
$ mvn clean install -Pfast -Dmaven.repo.local=repository --lax-checksums
# downloaded empty file
$ wget https://tigers-mannheim.de/nexus/repository/public/com/sleepycat/je/7.5.11/je-7.5.11.jar
```

Is the content broken? or no longer used to this project (but still registered to repository to be used) ?

**Comment by g3force** [comment]
Our Nexus servers recently replaced an artifact (com.sleepycat.je) by empty files for any reason (I assume, the Oracle Repo that we use as proxy had an issue and our Nexus fallback to jitpack which for any reason returned empty files....).

The artifact is already fixed on our Nexus, but you may still have issues when building, because the corrupt artifact is still in your local repository.

Just use the `clean.sh` script or delete the `repository` folder. If you do not want to download everything again, you can also just delete `repository/com/sleepycat`.

**Comment by kkimurak** [comment]
Thank you again, it was solved for me.
