### ISSUE TITLE
tag version-0.16.0 name pattern is causing error on build.gradle

### ISSUE THREAD

**Issue by FelipeMartins96** [TIGERs-Mannheim/AutoReferee#4]
https://github.com/TIGERs-Mannheim/AutoReferee/blob/3c98314dd4008e7e1ba4f06c5c226f0ec5f9bfc5/build.gradle#L18-L19

I guess the tag is named incorrectly as it does not match the build.gradle prefix and is different than older tags

**Comment by g3force** [comment]
Interesting. The tag `version-0.16.0` was created by GitHub. The other tags are correct. Do you get any error with this tag?

**Comment by g3force** [comment]
nevermind. I could reproduce the error. Let me have a look at it.

**Comment by g3force** [comment]
Should be fixed now.
You may need to remove the bad tag manually in your local repository (or clone the repo again).
Let me know if you still have problems and btw. thx for reporting.

**Comment by FelipeMartins96** [comment]
> Should be fixed now. You may need to remove the bad tag manually in your local repository (or clone the repo again). Let me know if you still have problems and btw. thx for reporting.

Thank you @g3force, I was able to build successfully after updating my local repo
