### ISSUE TITLE
build-in ssl-game-controller

### ISSUE THREAD

**Issue by xuanmingShang** [TIGERs-Mannheim/AutoReferee#5]
when push the button "start Game Controller", it present a warning "could not find ssl-game-controller in classpath" and i could not get the GC. how to solve this?

**Comment by g3force** [comment]
The GC is not included in the release by default. Use the latest version from here: https://github.com/RoboCup-SSL/ssl-game-controller/releases/tag/v3.5.3

I've added a note to the Readme, including instruction on how to build the autoRef with embedded GC: https://github.com/TIGERs-Mannheim/AutoReferee#activating-the-build-in-ssl-game-controller

**Comment by xuanmingShang** [comment]
thank you very much!

**Comment by xuanmingShang** [comment]
emmm, I have got another problem. I tried the "./gradlew :run -PcompactBuild=false" to use the embedded GC on the computer which also receives the vision from the cams. But it keep reporting "[visionfilter processor|camfilter] resetting cam filter for cam x", the x represents 0/1/2/3 for we have 4 cams in the field. Due to this, the visualizer keep blinking.

**Comment by g3force** [comment]
This means that you are receiving duplicate vision packets. Either because another ssl-vision or simulator is running, or because of a network issue. Typical cause is that packets are transmitted via wifi and lan at the same time.

**Comment by xuanmingShang** [comment]
actually, we have 2 computers to get the vision (2 cams each), and I configured the autoref on one of them. Is that beacause of this?

**Comment by g3force** [comment]
Are you using the latest ssl-vision version? Make sure that each is only publishing data for their two cameras.

There are two tools that I can recommend for the analysis (except from vision clients or tools like Wireshark):
* https://github.com/RoboCup-SSL/ssl-quality-inspector
* https://github.com/RoboCup-SSL/ssl-go-tools/tree/master/cmd/ssl-multicast-sources

**Comment by xuanmingShang** [comment]
ok, thank you, I'll try that

**Comment by xuanmingShang** [comment]
I have used the build-in GC by the note you add. And in the GC, I found that the switch with the name 'perform ball placement' in the 'start' cannot be closed. But ball placement maybe hard in the daily test. So I want to ask how to close it?

**Comment by g3force** [comment]
In division A, you can not disable ball placement, according to the rules. You can switch to division B, in which case the checkbox is enabled.
If you still want to test with division A rules, you could also go to the team configuration and change the number of ball placement failures to 5, which should disable ball placement as well.

**Comment by xuanmingShang** [comment]
Thanks a lot!
